<a href="https://colab.research.google.com/github/a01770768-oss/JobishViri/blob/main/class23sep.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
file_path = 'https://raw.githubusercontent.com/tec03/Datasets/refs/heads/main/datasets/AustralianWines.csv'
import pandas as pd
df = pd.read_csv(file_path)
df.head(2)

    Month Fortified Red  Rose   sparkling   Sweet white  Dry white
0  Jan-80      2585  464   112      1686.0         85.0     1954.0
1  Feb-80      3368  675   118      1591.0         89.0     2302.0

In [ ]:
df.shape

(188, 7)

In [ ]:
df.columns

Index(['Month', 'Fortified', 'Red ', 'Rose ', 'sparkling ', 'Sweet white',
       'Dry white'],
      dtype='object')

In [ ]:
favs = ['Red ', 'Rose ', 'sparkling ']

In [ ]:
df.loc[ :3, favs]

  Red  Rose   sparkling
0  464   112      1686.0
1  675   118      1591.0
2  703   129      2304.0
3  887    99      1712.0

In [ ]:
df.loc[ 10:19, favs]

    Red  Rose   sparkling
10   996   150      4087.0
11   960   267      5179.0
12   530   126      1530.0
13   883   129      1523.0
14   894   124      1633.0
15  1045    97      1976.0
16  1199   102      1170.0
17  1287   127      1480.0
18  1565   222      1781.0
19  1577   214      2472.0

In [ ]:
print('There are', df.shape[0], 'rows')
print('There are', df.shape[1], 'columns')

There are 188 rows
There are 7 columns